# -*- coding: utf-8 -*-
"""Лабораторная№1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WEJmgab_HzhDAAY3GJnJJLOtJDs0smlC
"""

print("Hello World")

a = 1
b = 4
c = a + b
print(c)

a = 10
b = 3
print(a % b)

a = float(input())
b = float(input())
print(a // b)

a = int(input())
b = int(input())
print(a * b)

a = 5
b = int(input())
c = a * b
print(c)

a = int(input())
b = int(input())
print((a + b) ** 2)

a = 15
b = 10
c = int(input())
print((a + b)//c)

a = int(input())
b = int(input())
print(a, '**2+', a, '*', b, '*2+', b, '**2', sep='')

a = float(input())
h = int(input())
s = (a*h)/2
print(s)

a = int(input())
b = int(input())
print(((a ** 3 + 14) // 5) * b)

a = int(input())
n = int(input())
print(a ** 2 // n)

a = float(input())
b = float(input())
c = int(input())
d = int(input())
print(a // b)
print(c * d)
print(c % d)

n = int(input())
print(n // 86400, 'Дней,', n // 3600, 'Часов,', n // 60, 'Минут')

n = int(input())
print(n + (n * n) + (n * n * n))