# -*- coding: utf-8 -*-
"""Лабораторная №6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12dTkl23swX4ETth7xl8AZTVOIcFdLPVr
"""

import matplotlib.pyplot as plt
fahrenheit = [[-67.0], [-34.0], [0], [34.0], [54.0], [67.0], [100]]
kelvin = [[218.15], [236.48], [255.37], [274.26], [285.37], [292.59], [310.92]]

plt.figure(figsize=(15,8), dpi=60)
plt.scatter(fahrenheit, kelvin, label='входные данные', color='green', marker='$f$');
plt.xlabel('fahrenheit')
plt.ylabel('kelvin')
plt.legend()
plt.grid(True)
plt.show()

for c, f in zip(fahrenheit, kelvin):
  print(f'фаренгейт{c}= кельвин {f}')

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(fahrenheit, kelvin)
lr.predict([[256], [123]])
lr.coef_
lr.intercept_
fahrenheit_test = [[-50], [10], [30], [20], [10], [70], [87]]
kelvin_test = lr.predict(fahrenheit_test)
kelvin_test

for c, f in zip(fahrenheit, kelvin):
  print(f'фаренгейт{c}= кельвин {f}')

import numpy as np
x_range = np.arange(-70,160)
y_range = (x_range+459.67) * 5/9
plt.figure(figsize=(15,8), dpi=280)
plt.plot(x_range, y_range, label='уравнение', linewidth='1')
plt.scatter(fahrenheit, kelvin, label='входные данные', color='green')
plt.scatter(fahrenheit_test, kelvin_test, label='предсказанное значение', color='blue')
plt.xlabel('Фаренгейта')
plt.ylabel('Кельвина')
plt.legend()
plt.grid(True)
plt.show()

import math
print(math.e)

import math
print(math.pi)

print(math.factorial(3))

print(math.gcd(3,64))