# -*- coding: utf-8 -*-
"""Лабораторная№3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wzyp3JBFOUPjEUtA4sLB3aKIbOX9o6Wq
"""

a = int(input())
if a == 1:
  print('Январь')
if a == 2:
  print('Февраль')
if a == 3:
  print('Март')
if a == 4:
  print('Апрель')
if a == 5:
  print('Май')
if a == 6:
  print('Июнь')
if a == 7:
  print('Июль')
if a == 8:
  print('Август')
if a == 9:
  print('Сентябрь')
if a == 10:
  print('Октябь')
if a == 11:
  print('Ноябрь')
if a == 12:
  print('Декабрь')

a = float(input())
b = float(input())
if a * 3.6 > b or b in float (range((-138/2) ** 1.3, abs((-69/28 ** 5.1) * 4))):
  c = a
  a = b
  b = c
  print(a, b) 
else:
  print(a, b)

otr = 0
ch = 0
a = 0  
a1 = int(input())
a2 = int(input())
a3 = int(input())
a4 = int(input())
a5 = int(input())
if a1 < 0:
    otr += 1
if a1 % 2 == 0:
  ch += 1
if a1 >= -256 and a1 <= 1024:
  a += 1
if a2 < 0:
    otr += 1
if a2 % 2 == 0:
  ch += 1
if a2 >= -256 and a2 <= 1024:
  a += 1
if a3 < 0:
    otr += 1
if a3 % 2 == 0:
  ch += 1
if a3 >= -256 and a3 <= 1024:
  a += 1
if a4 < 0:
    otr += 1
if a4 % 2 == 0:
  ch += 1
if a4 >= -256 and a4 <= 1024:
  a += 1
if a5 < 0:
    otr += 1
if a5 % 2 == 0:
  ch += 1
if a5 >= -256 and a5 <= 1024:
  a += 1
print('Отрицательных чисел:', otr, 'Четных чисел:', ch, 'Числа принадлежащие промежутку:', a)

a = int(input())
b = int(input())
c = int(input())
d = ((a ** 2 + b ** 3)/(c + 3))/4
if d % 2 == 0:
  print(d, 'Четное')
else:
  print(d, 'Нечетное')

a = int(input())
if a % 2 == 0:
  print('Чётное')
else:
  print('Нечётное')

n = int(input())
if n > 40:
  print('stonks')
else:
  print('not stonks')

year = int(input())
if year % 4 != 0:
  print('False')
else: 
  print('True')

n = int(input())
if n > 1:
  for i in range(2, n):
      if n % i == 0:
        print('False')
        break
  else:
    print(True)

a, b, c, d, e = int(input()), int(input()), int(input()), int(input()), int(input())
count = 0
otr = 0
5
print('Чётных чисел:', count)

print('Отрицательных чисел:', otr)